"""Add password hash

Revision ID: 084fe569e08a
Revises: 83d3e8a0343b
Create Date: 2025-12-15 17:10:50.512047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084fe569e08a'
down_revision = '83d3e8a0343b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
