"""add attachment columns

Revision ID: 5eef0b272862
Revises: 084fe569e08a
Create Date: 2025-12-18 12:13:21.804537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eef0b272862'
down_revision = '084fe569e08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###
